name: Lint and Test CI
on: [push]
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
